stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - data/raw/youtube_bulk_raw.csv
      - src/data/data_ingestion.py
      - params.yaml
    params:
      - data_ingestion.test_size 
    outs:
      - data/interim

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/interim/train.csv
      - data/interim/test.csv
      - config/slang_dict.json
      - params.yaml
    params:
      - data_preprocessing.remove_emojis
      - data_preprocessing.min_word_count
      - data_preprocessing.max_word_count
      - data_preprocessing.sentiment_model_name
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/features/feature_engineering.py   
    deps:
      - src/features/feature_engineering.py
      - data/processed/train_preprocessed.csv
      - data/processed/test_preprocessed.csv
      - params.yaml
    params:
      - feature_engineering.batch_size
    outs:
      - data/features   

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/features/features_train.npz
      - params.yaml
      - requirements.txt
    params:
      - model_building.random_state
      - model_building.n_folds
      - model_building.n_trials
      - model_building.early_stopping_rounds
    outs:
      - models/lightgbm_best_model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - models/lightgbm_best_model.pkl
      - data/features/features_test.npz
      - params.yaml
    outs:
      - artifacts/classification_report.json
      - artifacts/confusion_matrix.png  

  model_register:
    cmd: python src/model/model_register.py
    deps:
      - src/model/model_register.py
      - models/lightgbm_best_model.pkl
      - params.yaml
    params:
      - model_register.model_name
      - model_register.mlflow_tracking_uri
      - model_register.mlflow_experiment_name
      - model_register.model_version_file
    outs:
      - models/model_version.json  



   
  
