stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - data/raw/youtube_bulk_raw.csv
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/interim

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - data/interim/train.csv
      - data/interim/test.csv
      - src/data/data_preprocessing.py
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
      - src/features/feature_engineering.py
      - params.yaml
    params:
      - feature_engineering.max_features
      - feature_engineering.ngram_range
    outs:
      - data/features/train_features.pkl
      - data/features/test_features.pkl
      - data/features/tfidf_vectorizer.pkl
      - data/features/scaler.pkl

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/features/train_features.pkl
      - data/features/test_features.pkl
      - params.yaml
    params:
      - model_building.model_type
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
      - model_building.objective
      - model_building.eval_metric
    outs:
      - models/xgboost_best.pkl
      - models/env/conda.yaml
      - models/env/python_env.yaml
      - models/env/requirements.txt
      - confusion_matrix.png
      - experiment_info.json
    metrics:
      - metrics.json:
          cache: false 
      
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - models/xgboost_best.pkl
      - data/features/test_features.pkl
      - params.yaml
    outs:
      - reports/metrics.json
      - reports/confusion_matrix.png
