stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - data/raw/youtube_bulk_raw.csv
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/interim
