stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - data/raw/youtube_bulk_raw.csv
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/interim

  data_preprocessing: 
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/interim/train.csv
    - data/interim/test.csv
    - src/data/data_preprocessing.py
    outs:
    - data/processed
