data_ingestion:
   test_size: 0.2

feature_engineering:
   max_features: 10000        # Number of TF-IDF features to extract
   ngram_range: [1, 3]        # N-gram range for TF-IDF (1 = unigram, 3 = trigram)