data_ingestion:
  raw_data_path: data/raw/youtube_bulk_raw.csv
  interim_data_path: data/interim
  test_size: 0.20

data_preprocessing:
  train_input: data/interim/train.csv
  test_input: data/interim/test.csv
  output_path: data/processed
  remove_emojis: false
  sentiment_model_name: cardiffnlp/twitter-roberta-base-sentiment-latest
  min_word_count: 1
  max_word_count: 200
  slang_json: "config/slang_dict.json" 

feature_engineering:
  train_processed: "data/processed/train_preprocessed.csv"
  test_processed: "data/processed/test_preprocessed.csv"
  output_path: "data/features"
  batch_size: 256

model_building:
  random_state: 42
  n_folds: 3
  n_trials: 25
  early_stopping_rounds: 50
  model_dir: "models"
  mlflow_tracking_uri: "http://ec2-13-62-47-8.eu-north-1.compute.amazonaws.com:5000/"
  mlflow_experiment_name: "dvc_stage_sbert_lightgbm_hybrid"

model_evaluation:
  model_dir: "models"
  mlflow_tracking_uri: "http://ec2-13-62-47-8.eu-north-1.compute.amazonaws.com:5000/"
  mlflow_experiment_name: "dvc_stage_sbert_lightgbm_hybrid"

model_register:
  model_dir: models
  model_name: "yt_chrome_plugin_model"
  mlflow_tracking_uri: "http://ec2-13-62-47-8.eu-north-1.compute.amazonaws.com:5000/"
  mlflow_experiment_name: "dvc_stage_sbert_lightgbm_hybrid"
  model_version_file: "models/model_version.json"





