name: CICD pipeline

on:
  push:
    branches:
      - master

jobs:
  dvc-pipeline:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-north-1
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      #  Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      #  Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      #  Upgrade pip tools
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      #  Install project dependencies (ONLY ONCE)
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install pytest  textblob

      #  Verify AWS credentials
      - name: Verify AWS credentials
        run: aws sts get-caller-identity


      - name: Check AWS + botocore versions
        run: |
          python - <<EOF
          import boto3, botocore
          print("boto3:", boto3.__version__)
          print("botocore:", botocore.__version__)
          EOF
  

      #  Pull DVC artifacts
      - name: Pull DVC data
        run: dvc pull

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      #  Run tests
      - name: Run model registry tests
        run: pytest tests/test_model_registry.py -v

      - name: Run model signature tests
        run: pytest tests/test_model_signature.py -v

      - name: Run model performance tests
        run: pytest tests/test_model_performance.py -v

      - name: Run model permote from staging to production
        run: python scripts/promote_model.py 

      - name: Run Flask API tests
        run: |
          pytest tests/flask_api_test.py


